wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/assembly http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/assembly/ALUC-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/assembly http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/assembly/ALUC-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/assembly http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/assembly/ALUC-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/assembly http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/assembly/ALUC-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/assembly http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/assembly/ALUC-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/assembly http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/assembly/ALUC-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/assembly http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/assembly/ALUC-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/solexa-reads/ALUC-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P ALUC-Ipomoea_quamoclit/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/ALUC-Ipomoea_quamoclit/solexa-reads/ALUC-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/EMBR-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/solexa-reads/EMBR-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/solexa-reads/EMBR-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P EMBR-Ipomoea_pubescens/assembly/old-2010-08-31 http://web.corral.tacc.utexas.edu/OneKP/EMBR-Ipomoea_pubescens/assembly/old-2010-08-31/EMBR-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/assembly http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/assembly/ERWT-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/solexa-reads/ERWT-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P ERWT-Ipomoea_coccinea/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/ERWT-Ipomoea_coccinea/solexa-reads/ERWT-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/assembly http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/assembly/IZNU-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/solexa-reads/IZNU-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P IZNU-Ipomoea_lobata/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/IZNU-Ipomoea_lobata/solexa-reads/IZNU-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/assembly http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/assembly/NAUM-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/solexa-reads/NAUM-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P NAUM-Ipomoea_lindheimeri/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/NAUM-Ipomoea_lindheimeri/solexa-reads/NAUM-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/assembly http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/assembly/NHAG-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/solexa-reads/NHAG-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P NHAG-Ipomoea_nil/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/NHAG-Ipomoea_nil/solexa-reads/NHAG-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/assembly http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/assembly/OQBM-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/solexa-reads/OQBM-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P OQBM-Ipomoea_indica/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/OQBM-Ipomoea_indica/solexa-reads/OQBM-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/assembly http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/assembly/QSLH-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/solexa-reads/QSLH-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P QSLH-Ipomoea_hederacea/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/QSLH-Ipomoea_hederacea/solexa-reads/QSLH-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/assembly http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/assembly/SDXI-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/assembly http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/assembly/SDXI-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/assembly http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/assembly/SDXI-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/assembly http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/assembly/SDXI-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/assembly http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/assembly/SDXI-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/assembly http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/assembly/SDXI-assembly.fa_blastx.results.bz2
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/assembly http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/assembly/SDXI-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/solexa-reads/SDXI-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P SDXI-Ipomoea_purpurea-leaf/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/SDXI-Ipomoea_purpurea-leaf/solexa-reads/SDXI-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea/solexa-reads/40_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea/solexa-reads/40_files/VXKB-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea/solexa-reads/40_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea/solexa-reads/40_files/VXKB-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea/solexa-reads/69_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea/solexa-reads/69_files/VXKB-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea/solexa-reads/69_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea/solexa-reads/69_files/VXKB-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea/assembly/VXKB-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea/assembly/VXKB-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea/assembly/VXKB-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/VXKB-BGI_statistics.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/VXKB-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/VXKB-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/VXKB-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/VXKB-assembly.fa_blastx.results
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/VXKB-intermediate_outputs.tar.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/VXKB-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/VXKB-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/old-2010-08-31 http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/assembly/old-2010-08-31/VXKB-scaffold.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/40_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/40_files/VXKB-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/40_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/40_files/VXKB-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/69_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/69_files/VXKB-read_1.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/69_files http://web.corral.tacc.utexas.edu/OneKP/VXKB-Ipomoea_purpurea-leaf_stem_flower/solexa-reads/69_files/VXKB-read_2.fq.bz2
wget --user=1kp-data --password='1kp-rna1' -P XQRV-Ipomoea_purpurea-2_samples_combined/assembly http://web.corral.tacc.utexas.edu/OneKP/XQRV-Ipomoea_purpurea-2_samples_combined/assembly/XQRV-SOAPdenovo-Trans-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P XQRV-Ipomoea_purpurea-2_samples_combined/assembly http://web.corral.tacc.utexas.edu/OneKP/XQRV-Ipomoea_purpurea-2_samples_combined/assembly/XQRV-SOAPdenovo-Trans-assembly.fa.bz2_blastx
wget --user=1kp-data --password='1kp-rna1' -P XQRV-Ipomoea_purpurea-2_samples_combined/assembly http://web.corral.tacc.utexas.edu/OneKP/XQRV-Ipomoea_purpurea-2_samples_combined/assembly/XQRV-SOAPdenovo-Trans-assembly.fa.bz2_report
wget --user=1kp-data --password='1kp-rna1' -P XQRV-Ipomoea_purpurea-2_samples_combined/assembly http://web.corral.tacc.utexas.edu/OneKP/XQRV-Ipomoea_purpurea-2_samples_combined/assembly/XQRV-assembly.fa.bz2
wget --user=1kp-data --password='1kp-rna1' -P XQRV-Ipomoea_purpurea-2_samples_combined/assembly http://web.corral.tacc.utexas.edu/OneKP/XQRV-Ipomoea_purpurea-2_samples_combined/assembly/XQRV-assembly.fa_blastx.results.bz2
